Fpad 984 take 2
govuk-one-login/fraud-npm pull request #2
Opened 2023-11-19 13:53 UTC by tbrown224

2023-11-20 16:18 UTC, aholwellGDS requested changes

2023-11-20 16:18 UTC, aholwellGDS commented on logging/log-events.ts
> +}
I think the log events should probably remain in the specific repo that uses them. All apart from the top 3 at least as they're not really general.

2023-11-24 19:03 UTC, tbrown224 commented on .github/workflows/publish.yaml
> +      - run: npm ci
Done

2023-11-24 19:03 UTC, tbrown224 commented on package.json
Removed

2023-11-24 19:04 UTC, tbrown224 commented on logging/package.json
Removed package.json from root folder and kept the package.json within /logging directory

2023-11-24 19:04 UTC, tbrown224 commented on jest.config.ts
Done

2023-11-24 19:04 UTC, tbrown224 commented on logging/logging.ts
This is out of scope of this ticket and will therefor raise a separate ticket to address these changes

2023-11-27 11:43 UTC, aholwellGDS approved these changes

2023-12-01 16:11 UTC, merged